version: "3"

services:
  frontend:
    restart: always
    build:
      context: ./app
    depends_on:
      - backend

  backend:
    hostname: backend-api
    restart: always
    ports:
      - 3001:3001
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:alpine3.19
    restart: always
    ports:
      - 6379:6379
    command: redis-server

  mongodb:
    restart: always
    image: mongo:5.0.2
    env_file: ./.env
    command:
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  webserver:
    container_name: "webserver"
    image: "nginx:latest"
    restart: unless-stopped
    ports:
      - "80:80" # Redirect HTTP to HTTPS
      - "443:443" # HTTPS traffic
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    depends_on:
      - webserver
    command: certonly --webroot -w /var/www/certbot --force-renewal --register-unsafely-without-email -d talent-tune.holk.solutions --agree-tos -v

volumes:
  db:
