version: "3"

services:
  webserver:
    image: "nginx:latest"
    restart: unless-stopped
    ports:
      - "80:80" # Redirect HTTP to HTTPS
      - "443:443" # HTTPS traffic
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - webserver
    command: certonly --webroot -w /var/www/certbot --force-renewal --register-unsafely-without-email -d talent-tune.holk.solutions --agree-tos -v
