name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            cd talent-tune
            git checkout main
            git pull
            docker-compose -f docker-compose-production.yml up --build -d
